#9 textbox for user address input
drkchn/mosa-upenn-SoC-2023 pull request #31
Opened 2023-06-20 20:04 UTC by drkchn

Changes made
- Added text box for user to input their residential address
- Added sample addresses that rotate within the text box after timer
- Added icon next to text box to symbolize residential address
- Added button with icon to stylize button
- Added text to describe and welcome users when they visit the home page
- Changed colors to match our theme
- Formatted homepage

Visual of the homepage
![Homepage](https://github.com/drkchn/mosa-upenn-SoC-2023/assets/57195399/39cc0888-4baf-4b6e-b99f-704b26afc890)

2023-06-20 22:59 UTC, drkchn commented
Hi @cfech Can you see this comment? I'm trying to figure out why I can't see your feedback

2023-06-20 23:39 UTC, cfech requested changes

2023-06-21 02:54 UTC, drkchn commented on src/Pages/Home/Home.tsx
> +const MyComponent: React.FC = () => {
I moved the code to its file called `HomepageSearchBar.tsx`, and it's now located in the components folder

2023-06-21 04:28 UTC, cfech approved these changes

2023-06-21 04:29 UTC, cfech commented
Made a few changes this commit https://github.com/drkchn/mosa-upenn-SoC-2023/commit/2a1041f4a0f093b90b6d08ca2973f0a8352314c1 to keep using MUI instead of html, use react export and keep the button and search bar together for easier state management

2023-06-21 04:30 UTC, merged